# Generated by Django 3.1 on 2020-08-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25, unique=True)),
                ('project_detail', models.CharField(max_length=150)),
                ('project_image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, unique=True)),
                ('student_deadline', models.DateField()),
                ('student_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilestoneApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25, unique=True)),
                ('task_description', models.CharField(max_length=150)),
                ('task_deadline', models.DateField()),
                ('task_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MilestoneApp.student')),
            ],
        ),
    ]
