# Generated by Django 3.1 on 2020-08-18 16:31

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MilestoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='media'),
        ),
    ]
